### ISSUE TITLE
World Map labels and mouse event

### ISSUE THREAD

**Issue by jose383** [jose383/covid-19#1]
Add labels to the world map displaying the country's name and add the mouse event so when you hover on a country it shows the data results.

**Comment by KevinCrespin** [comment]
Feature already added to P2G1

**Comment by pareshgami** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
adriandelgg, @Erick0877, @cheekybastard, @canhngo00, @dasibcryptoidology, @godlovedamian, @gutek2, @Brikulya, @Anon79, @mackseb, @YourShawn, @Sim12courtney, @NgVQuang, @eliasbuchwald, @troywsmith, @Notmanhero, @Redwarrio, @Andrea337, @michaelschultzdev, @jer0d, @jpcloureiro, @anghelloerr, @kevin71089, @yogiartnft, @14282, @bffcorreia, @SiboldSiborg, @Yunus1996, @markrachapoom, @Bierstuff, @Adiltonzs, @cemontijo, @pelhage, @lompo011, @spade-zd, @TinyRick941, @attarian001, @kelcheone, @Marcin199626, @danielng620, @Mahmoudshahir, @RashadAnsari, @oasissoman, @awalo666, @cb-kfroemming, @Sadeghi1017, @antaintan, @shanefontaine, @Anthonyfrankudoka, @Mlmolefe2
